nyc_tlc_analytics_warehouse:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_PROD_DATASET', 'nyc_tlc_prod') }}"
      location: "{{ env_var('GCP_REGION', 'us-central1') }}"
      threads: 4
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
