version: "3.9"

services:
  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    volumes:
      - ./dbt:/usr/app/dbt
      - ./keys:/usr/app/keys:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/app/keys/gcp-service-account.json
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - BQ_RAW_DATASET=${BQ_RAW_DATASET:-ecommerce_raw}
      - BQ_PROD_DATASET=${BQ_PROD_DATASET:-ecommerce_prod}
      - GCP_REGION=${GCP_REGION:-us-central1}
    working_dir: /usr/app/dbt
    entrypoint: ["dbt"]
    command: ["run"]
